# Generated by Django 3.1.4 on 2023-05-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='export',
            name='title',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
