# Generated by Django 3.1.4 on 2023-06-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20230601_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
