# Generated by Django 3.1.4 on 2023-06-01 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_auto_20230601_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='export',
            old_name='page_size',
            new_name='list_size',
        ),
    ]
