# Generated by Django 4.2.4 on 2023-08-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0007_auto_20230602_0023"),
    ]

    operations = [
        migrations.AlterField(
            model_name="export",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="importfile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="importsheet",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
