# Generated by Django 4.2.4 on 2023-11-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0009_auto_20230920_1404"),
    ]

    operations = [
        migrations.AlterField(
            model_name="export",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="importfile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="importsheet",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
