# Generated by Django 3.1.4 on 2024-05-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_alter_export_id_alter_importfile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='export',
            name='list_size',
            field=models.IntegerField(choices=[(5, '5'), (10, '10'), (20, '20'), (50, '50'), (100, '100'), (300, '300'), (500, '500'), (800, '800'), (1000, '1000'), (10000, '10000')], default=20),
        ),
        migrations.AlterField(
            model_name='importfile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='importsheet',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
